import React from 'react';
import type { Metadata } from 'next';
import type { NextFont } from 'next/dist/compiled/@next/font';
import { Inter } from 'next/font/google';

import './globals.css';

const inter: NextFont = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'My first React application',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
