name: Node.js CI

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      TEST_LOGIN: ${{ vars.TEST_LOGIN }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
    defaults:
      run:
        working-directory: .

    steps:
      - name: Git checkout repo
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install NPM packages and build
        run: npm ci && npm run build

      - name: Start App
        run: nohup npm run start &

      - name: Run E2E tests in the Chrome browser
        uses: cypress-io/github-action@v6
        with:
          working-directory: .
          config: defaultCommandTimeout=10000,video=true,retries=2,baseUrl=http://localhost:3000
          browser: chrome
          quiet: true

      - name: Make E2E test report
        if: ${{ always() }}
        run: |
          npx mochawesome-merge coverage/cypress/results/*.json > coverage/cypress/results/combined.json
          npx marge coverage/cypress/results/combined.json -f e2e -t "HTDL E2E" -p "HTDL E2E test report" -o coverage/cypress/
          rm -rf coverage/cypress/results
          rm -rf coverage/phpunit.cache

      - name: Upload all test reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: all-test-reports
          path: |
            coverage/**/*
          if-no-files-found: ignore
          retention-days: 7
